services:
  frouros:
    build:
      context: .
      dockerfile: Dockerfile.cpu

    container_name: frouros-ai

    user: "${UID}:${GID}"
    group_add:
      - "44"
    env_file:
      - .env
    environment:
      HOME: /home/appuser
      TRITON_CACHE_DIR: /tmp/triton
      XDG_CACHE_HOME: /home/appuser/.cache
      HF_HOME: /home/appuser/.cache/huggingface
      TORCH_HOME: /home/appuser/.cache/torch
      MPLCONFIGDIR: /home/appuser/.config/matplotlib
      YOLO_CONFIG_DIR: /home/appuser/.config/Ultralytics

    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1


    volumes:
      - .:/app
      - ~/.cache/huggingface:/home/appuser/.cache/huggingface
      - ~/.cache/torch:/home/appuser/.cache/torch
      - ~/.cache/ultralytics:/home/appuser/.config/Ultralytics

    working_dir: /app

    stdin_open: true
    tty: true
