FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime

WORKDIR /app
ENV PYTHONPATH=/app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    git \
    python3-dev \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libxcb1 \
    ffmpeg && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.cpu.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.cpu.txt

COPY . .

CMD ["python", "src/main.py"]